Repository epsagon/otel-js, pull requests merged in 2022-03, with the labels that each got.

#63 Feat/add system tests
  .github/workflows/ci.yaml
  .github/workflows/prettier.yml
  system-tests/docker-compose.yaml
  system-tests/server/Dockerfile
  system-tests/server/package-lock.json
  system-tests/server/package.json
  system-tests/server/server.js
Labels: size/M

#64 feat(version): my first commit
  .github/workflows/ci.yaml
  .gitignore
  package-lock.json
  src/tracing.ts
  src/version.ts
  system-tests/server/Dockerfile
  tsconfig.json
Labels: size/M

#68 feat(exporter): added customHeaders feature
  README.md
  codecov.yml
  src/exporter-factory.ts
  src/options.ts
  src/version.ts
  test/exporter-tracing.test.ts
  test/options.test.ts
  test/tracing.test.ts
Labels: size/M

#69 fix(aws-sns-test): add test with nock to sns publish
  .github/workflows/ci.yaml
  codecov.yml
  package-lock.json
  package.json
  src/instrumentations/extentions/aws/SNSEventCreator.ts
  test/instrumentatios/extentions/aws-mock-responses/sns-publish.xml
  test/instrumentatios/extentions/aws_sdk_v3.test.ts
Labels: size/L

#70 fix(cisco-specs): adapted cisco POC specs
  package-lock.json
  package.json
  src/instrumentations/extentions/http.ts
  test/instrumentatios/extentions/http.test.ts
Labels: size/M

#71 fix(aws-sqs-test): add sqs test
  package-lock.json
  package.json
  test/instrumentatios/extentions/aws-mock-responses/sqs-send-message-batch.xml
  test/instrumentatios/extentions/aws-mock-responses/sqs-send-message.xml
  test/instrumentatios/extentions/aws_sdk_v3.test.ts
Labels: size/L

#72 fix(aws-sqs): add test for receiveMessage
  package-lock.json
  test/instrumentatios/extentions/aws-mock-responses/sqs-receive-message.xml
  test/instrumentatios/extentions/aws_sdk_v3.test.ts
Labels: size/M

#73 fix(sqs-receive-msg): add case of multiple msgs
  test/instrumentatios/extentions/aws-mock-responses/sqs-receive-message-more-than-one.xml
  test/instrumentatios/extentions/aws_sdk_v3.test.ts
Labels: size/M

#66 Feat/add resource detectors
  README.md
  package-lock.json
  package.json
  src/tracing.ts
  test/tracing.test.ts
Labels: size/M

#75 Fix/adapt cisco semvconv
  package-lock.json
  package.json
  src/instrumentations/extentions/amqplib.ts
  src/instrumentations/extentions/aws/DynamoDBEventCreator.ts
  src/instrumentations/extentions/aws/SNSEventCreator.ts
  src/instrumentations/extentions/aws/SQSEventCreator.ts
  src/instrumentations/extentions/http.ts
  src/instrumentations/extentions/redis.ts
  src/instrumentations/static-instrumentations/grpc-js/clientUtils.ts
  src/instrumentations/static-instrumentations/grpc-js/instrumentation.ts
  src/instrumentations/static-instrumentations/grpc-js/serverUtils.ts
  src/instrumentations/utils/utils.ts
  test/instrumentatios/extentions/amqplib.test.ts
  test/instrumentatios/extentions/aws_sdk_v3.test.ts
  test/instrumentatios/extentions/http.test.ts
  test/instrumentatios/extentions/redis.test.ts
  test/instrumentatios/static-instrumentations/grpc-js/grpc-js.test.ts
  test/instrumentatios/utils/PayloadHandler.test.ts
Labels: size/L

#76 fix(resource): added otel service name to resource
  src/tracing.ts
Labels: size/XS

#77 fix(package.json): fixed otel deps
  package-lock.json
  package.json
Labels: size/XS
