Repository epsagon/otel-js, pull requests merged in 2022-02, with the labels that each got.

#42 Feat/add exporter option
  README.md
  package-lock.json
  package.json
  src/exporter-factory.ts
  src/options.ts
  src/tracing.ts
  test/exporter-tracing.test.ts
  test/options.test.ts
  test/tracing.test.ts
Labels: size/L

#45 Add redis payloads
  package-lock.json
  package.json
  src/instrumentations/extentions/aws/DynamoDBEventCreator.ts
  src/instrumentations/extentions/aws/SNSEventCreator.ts
  src/instrumentations/extentions/aws/SQSEventCreator.ts
  src/instrumentations/extentions/aws/aws_sdk.ts
  src/instrumentations/extentions/aws/event-creator-interface.ts
  src/instrumentations/extentions/redis.ts
  src/instrumentations/index.ts
Labels: size/XL

#47 Feat/muti exporter/sdk 348
  README.md
  src/exporter-factory.ts
  src/options.ts
  src/tracing.ts
  test/exporter-tracing.test.ts
  test/options.test.ts
Labels: size/L

#50 feat(amqp): added amqp instrumentation
  package-lock.json
  package.json
  src/instrumentations/index.ts
Labels: size/XS

#49 Feat/muti exporter/sdk 348
  README.md
  src/exporter-factory.ts
  src/options.ts
  test/app.ts
  test/exporter-tracing.test.ts
  test/instrumentatios/extentions/http.test.ts
  test/instrumentatios/utils/HttpBodyHandler.test.ts
  test/options.test.ts
  test/tracing.test.ts
Labels: size/L

#51 Add redis payloads
  .github/workflows/ci.yaml
  package-lock.json
  package.json
  src/instrumentations/extentions/aws/DynamoDBEventCreator.ts
  src/instrumentations/extentions/aws/SNSEventCreator.ts
  src/instrumentations/extentions/aws/SQSEventCreator.ts
  src/instrumentations/extentions/aws/aws_sdk.ts
  src/instrumentations/extentions/aws/event-creator-interface.ts
  src/instrumentations/extentions/redis.ts
  src/instrumentations/index.ts
  test/instrumentatios/extentions/redis.test.ts
Labels: size/L

#52 Feat/add rabbitmq payloads
  .eslintignore
  .github/workflows/ci.yaml
  package-lock.json
  package.json
  src/instrumentations/extentions/amqplib.ts
  src/instrumentations/extentions/http.ts
  src/instrumentations/index.ts
  src/instrumentations/utils/PayloadHandler.ts
  src/instrumentations/utils/utils.ts
  test/instrumentatios/extentions/amqplib.test.ts
  test/instrumentatios/extentions/http.test.ts
  test/instrumentatios/extentions/redis.test.ts
  test/instrumentatios/utils/HttpBodyHandler.test.ts
  test/instrumentatios/utils/PayloadHandler.test.ts
  test/utils.ts
Labels: size/XXL

#43 ci: added prettify to ci
  .commitlintrc.yml
  .eslintrc.js
  .github/workflows/prettier.yml
  README.md
  codecov.yml
  test/config.yaml
Labels: size/L

#53 fix(codecov): added codecov
  .github/workflows/ci.yaml
Labels: size/XS

#55 fix(readme): fixed otel-js badges
  README.md
Labels: size/XS

#57 fix(readme): fixed aligning
  README.md
Labels: size/XS

#58 fix(package-json): after run npm audit fix
  package-lock.json
Labels: size/XS

#59 fix(package-json): after run npm audit fix
  package-lock.json
  package.json
Labels: size/S

#56 chore: fixed typo
  README.md
Labels: size/S

#60 Fix/adjust cisco naming
  README.md
  src/exporter-factory.ts
  src/index.ts
  src/instrumentations/extentions/amqplib.ts
  src/instrumentations/index.ts
  src/instrumentations/utils/PayloadHandler.ts
  src/options.ts
  src/tracing.ts
  test/app.ts
  test/exporter-tracing.test.ts
  test/instrumentatios/extentions/amqplib.test.ts
  test/instrumentatios/extentions/http.test.ts
  test/instrumentatios/extentions/redis.test.ts
  test/instrumentatios/utils/PayloadHandler.test.ts
  test/options.test.ts
  test/tracing.test.ts
  test/utils.ts
Labels: size/L

#62 fix(redis): fix redis specification
  src/instrumentations/extentions/redis.ts
  test/instrumentatios/extentions/redis.test.ts
Labels: size/S
